Capstone project:HTML-CSS-JavaScript-Capstone-Project
Tumworobere/HTML-CSS-JavaScript-Capstone-Project pull request #2
Opened 2021-10-22 05:39 UTC by Tumworobere

In this project,i implemented the following.
**Mobile version of the page**
-When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
-The mobile menu has a close (X) button that closes the menu.
**Desktop version of the page**
Interactions
.The home page has a link in the menu to the about page.
-The logo in the header links to the home page.
Dynamic page
The section "Featured speakers" is created dynamically in JavaScript.
I used use a JavaScript variable with the data about the speakers used when the page loads to create the HTML for this section dynamically.

2021-10-22 09:06 UTC, eliasecasta requested changes
# Status:  Changes Required ♻️
_Check the comments under the review_
<hr>

Hello @Tumworobere, I am Elias, your reviewer for this PR

Well done so far with your project!

I really liked the front page design that you used, it looks colorful and great! You also placed a lot of attention on little details, your menu is working really well and you gave a nice twist to the webpage, great job so far with your project, you are almost done!

I will mention to you a small summary of things that need to be changed in order to keep moving:

- [ ] Please record a video covering these details and place the link of it in this PR: 

![image](https://user-images.githubusercontent.com/38522578/138424436-e769ab53-0a98-4f74-9d1f-1fe045b6d5ac.png)

- [ ] The page needs to be built with mobile-first in mind.
- [ ] You are missing some really small positioning details.
- [ ] Please check the requirements below for more information and requirements about this review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please correct those issues and send another review request, good luck, and well done so far! 

Code review by Elias Castañeda

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561) you have a limited number of code reviews per project (you can check the exact number in your Dashboard). If you think that the code review was not fair, you can [request a second opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-22 09:06 UTC, eliasecasta commented on about.html
> +                                <a href="#"><i class="fa fa-twitter fa-2x"></i></a>
- [ ] Please make the height of the social network icons smaller to match the height of the rest of the elements placed in the black navbar to have similar sizes to the ones provided in the design so we can comply with the project requirements:

![image](https://user-images.githubusercontent.com/38522578/138419998-99073920-d8e1-47b8-8dc6-b4c9f89e3b78.png)

2021-10-22 09:06 UTC, eliasecasta commented on index.html
> +            </section>
- [ ] Please remove some of this space or move down all the elements a little bit more to center them so we don't have that much noticeable empty space:

![image](https://user-images.githubusercontent.com/38522578/138420444-8f3b3930-5d86-4ef0-8ff3-0db7fc177292.png)

2021-10-22 09:06 UTC, eliasecasta commented on index.html
> +            </section>
- [ ] [OPTIONAL]: You can adapt this main program section to tablet view in order to avoid this text-overflow that is happening with your titles, this is to make your project look as professional as possible 👍 

![image](https://user-images.githubusercontent.com/38522578/138420887-2ea4768d-9ff8-4f48-a402-1e6fa090d92d.png)

2021-10-22 09:06 UTC, eliasecasta commented on index.html
> +                    <h2>Featured Speakers</h2>
- [ ] Please normalize the image sizes used for the featured speakers, currently, they have different heights from the desktop view and they break more if I play a little bit with the width of the webpage:

![image](https://user-images.githubusercontent.com/38522578/138421440-668b0467-a425-4cb7-8c44-2a77e5c92b04.png)

![image](https://user-images.githubusercontent.com/38522578/138421506-44ca98a0-a905-4f46-bc10-7f31aa7573e5.png)

2021-10-22 09:06 UTC, eliasecasta commented on about.html
> +            Partner
- [ ] Please remove some of the bottom space of this element to comply with the project requirements.

![image](https://user-images.githubusercontent.com/38522578/138421777-15d8de6a-6714-408e-906e-fd7d47e527df.png)

2021-10-22 09:06 UTC, eliasecasta commented on about.html
> +    <h4>2021 GHC Conference  .  Some Rights Reserved</h4>
- [ ] Please align this text to the center of the logo image to the left of it to comply with the project requirements:

![image](https://user-images.githubusercontent.com/38522578/138421908-6aa7f979-f070-484c-b10c-97db296b64ce.png)

2021-10-22 09:06 UTC, eliasecasta commented on about.html
> +        <img src="./images/first-content.png" alt="about image">
- [ ] This image appears to be broken, please take a second look at it and fix it to comply with the project requirements:

![image](https://user-images.githubusercontent.com/38522578/138422097-0010aac3-e862-4bb4-b010-f0231c96db14.png)

2021-10-22 09:06 UTC, eliasecasta commented on about.html
> +            !<br><strong>anitab@ghc.org</strong></p>
- [ ] Please add some margin/padding to the bottom of this element to have a similar one as the one provided in the design so we can comply with the project requirements:

![image](https://user-images.githubusercontent.com/38522578/138422283-9d4096de-c5f5-4062-8640-733b438307eb.png)

2021-10-22 09:06 UTC, eliasecasta commented on about.html
> +        <p>The logo of GHC Annual Conference 2021 was decided throught the logo competition form 8.June to 7.July.
- [ ] Please insert a small separator as you did in multiple parts of this project so we can comply with the project requirements:

![image](https://user-images.githubusercontent.com/38522578/138422468-33f8f967-02d0-449f-a5fd-97ef12bdf5c1.png)

2021-10-22 09:06 UTC, eliasecasta commented on index.html
> +                            <div class="div3 w-50 text-center">
- [ ] The white text should be aligned to the left in the mobile view, please correct it in order to match the design provided (I suggest you to make the icons a little smaller in order to fit more text, also, the cards can be a little wider, you have some unused space in the borders that can help you fitting that text properly):

Your current design:

![image](https://user-images.githubusercontent.com/38522578/138422907-731626ab-7c10-4a3c-b6c7-b119270e7f81.png)

Provided design:

![image](https://user-images.githubusercontent.com/38522578/138422964-8f53ebb2-f629-44a6-86bc-3296f9169365.png)

2021-10-22 09:06 UTC, eliasecasta commented on index.html
> +    </footer>
- [ ] Your footer should be black in desktop view but it should turn white while in mobile view, please handle this with media queries in order to comply with the project requirements.

![image](https://user-images.githubusercontent.com/38522578/138423465-075d3ec5-bffa-4b63-aafa-5cba78014dc4.png)

2021-10-22 09:06 UTC, eliasecasta commented on about.html
> +        <p>The logo of GHC Annual Conference 2021 was decided throught the logo competition form 8.June to 7.July.
- [ ] This text must be centered in mobile view, please do so to comply with the project requirements:

![image](https://user-images.githubusercontent.com/38522578/138423705-e31fed88-be81-47a5-a1e8-54f990881971.png)

2021-10-22 09:06 UTC, eliasecasta commented on index.html
> +                            </div>
- [ ] Please make use of the `<article>` tag wherever necessary through your HTML files in order to comply with HTML best practices and semantics.

2021-10-22 09:06 UTC, eliasecasta commented on about.html
> +<body>
- [ ] Please make use of one `<h1>` tag in the about HTML to improve your webpage SEO punctuation.

2021-10-22 09:06 UTC, eliasecasta commented on css/style.css
> +}
- [ ] Correct me if I am mistaken but I think that you started building your CSS styling from desktop and then adapted it to mobile. This project strictly requires you to style it with mobile-first methodology in mind. Please do so to comply with the project requirements.

2021-10-22 22:32 UTC, rloterh commented on about.html
> +                                <a href="#"><i class="fa fa-twitter fa-2x"></i></a>
This issue is well resolved! ✔️

2021-10-22 22:49 UTC, rloterh commented on index.html
> +            </section>
This section needs further improvements:
- [ ] Kind ensure that the content within this section is almost **horizontally centered**, as can be seen from the template design. That is, kindly ensure the space above and below the contents should be almost the same. Please remember to be guided by the template design.

**Your design:**
![image](https://user-images.githubusercontent.com/12745474/138530769-bf7aa166-9c7c-4fac-920b-36fcc4b74434.png)


**The original design:**
![image](https://user-images.githubusercontent.com/12745474/138530847-7f822448-b19a-4968-b3d4-415631cdf8a1.png)

2021-10-22 22:49 UTC, rloterh commented on index.html
> +            </section>
This issue is well resolved! ✔️

2021-10-22 22:49 UTC, rloterh commented on index.html
> +                    <h2>Featured Speakers</h2>
This issue is well resolved! ✔️

2021-10-22 23:22 UTC, rloterh commented on index.html
> +                                <h3>Session</h3>
- [ ] OPTIONAL
Your code is **not properly indented** and therefore your code formatting is inconsistent. Kindly ensure that your code has consistent **spacing** for indentation. The recommended spacing is **2 spaces**. You can install and configure a code formatter plugins such as [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) or [Beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) in your code editor for formatting your code to ensure consistent and well-indented code.

2021-10-22 23:22 UTC, rloterh commented on .gitignore
> +node_modules
- [ ] OPTIONAL
The `.vscode` is appearing in your project structure. It's a good practice to keep all files and folders which are irrelevant to the project development in the `.gitignore` file. Kindly endeavor to the `.vscode` directory, as well as other _less important files_ in the `.gitignore` list.

2021-10-22 23:22 UTC, rloterh commented on about.html
> +            Partner
This section needs further improvements:
- [ ] Kind ensure that the content within this section is almost **horizontally centered**, as can be seen from the template design. That is, kindly ensure the space above and below the contents should be almost the same. Please remember to be guided by the template design.

**Your design:**
![image](https://user-images.githubusercontent.com/12745474/138531680-76603eca-7377-4774-a0c3-3c72fcaad229.png)



**The original design:**
![image](https://user-images.githubusercontent.com/12745474/138531694-239eb63f-c5d7-4a01-a930-634cf83ff10c.png)

2021-10-22 23:22 UTC, rloterh commented on about.html
> +    <h4>2021 GHC Conference  .  Some Rights Reserved</h4>
The section needs further improvements:
- [ ] Kind ensure that the contents within this section are **horizontally centered**, as can be seen from the template design. Please remember to be guided by the template design.

**Your design:**
![image](https://user-images.githubusercontent.com/12745474/138532079-d7957670-9262-493c-ae50-8759a4c59079.png)


**The original design:**
![image](https://user-images.githubusercontent.com/12745474/138532254-fe5b005f-a462-4e2a-a91d-61464fbe3c52.png)

2021-10-22 23:22 UTC, rloterh commented on about.html
> +<body>
This issue is well resolved! ✔️

2021-10-22 23:30 UTC, rloterh requested changes
Hi , 

You did great on this project, and for making the changes requested by the previous reviewer! 👏👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 🚦  

## Good Points 👍  
- Descriptive Pull Request
- Good presentation of the project
- Nice to recognize Cindy Shin, the author of the original design in your acknowledgment section
Project hosted on Github pages and working
The dynamic aspect is well implemented
Great UI design
Good ReadMe

## Required Changes ♻️
_Kindly check the comments above, made under the reviews of the previous code reviewer(s) and stating **not properly resolved**. Kindly take your time to correctly review those issues outlined by the previous code reviewers, and please check to see that the changes are working as intended._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly consider the comments marked **[OPTIONAL]** under this review:

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 3 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-22 23:30 UTC, rloterh commented on index.html
> +            </section>
- [ ] OPTIONAL
Kindly add enough spacing (padding or margin) to the top and bottom to the contents of the white navbar. Please be guided by the [template design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)


**Your design:**
![image](https://user-images.githubusercontent.com/12745474/138532988-8f6bcc8c-8bf0-43c6-b80f-e8c0a5a71a70.png)

**The original design:**
![image](https://user-images.githubusercontent.com/12745474/138533013-d6e793ca-1d1a-46a1-820d-996016dbfade.png)

2021-10-23 17:36 UTC, bini-i approved these changes
# Status: Approved :heavy_check_mark:          
### Hello @Tumworobere  :wave: 

Thanks for working on the requirements suggested by the previous reviewers.
**Congratulations**, your project meets all the requirements and it is **approved** :tada:.

#### To highlight
- You have customized the site well while keeping color, typography and page structure from the design given.
- Good video presentation of the project done and you can also give some highlight of the code implemented to further better your presentation.

> Reminder: [Optional]
- I think it would be nice if you work on some elements overflowing out of screen in mobile view, to make your site more professional and grab attention visitiors to further explore your projects:
- eg: 
![Screenshot](https://user-images.githubusercontent.com/61377322/138566068-ed759fc2-e1fd-4538-ac0d-ad2979d86d58.png)
- Footer section
![image](https://user-images.githubusercontent.com/61377322/138566160-f0a3cca7-5885-4660-a816-ab46a79599ec.png)
- About section (as shown below it is rendering `alt` attribute of `img` instead of the image itself, try resolving the path to the image)
![image](https://user-images.githubusercontent.com/61377322/138566193-471ac3e9-2b47-4275-8130-b68881cd283d.png)



#### If you have any questions feel free to ask within the PR thread.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (Code Reviewer)
> GitHub: [@bini-i](https://github.com/bini-i) 
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

2022-02-16 06:59 UTC, merged